services:

    energyplus_ai:
        container_name: "energyplus_ai"
        image: "energyplus_ai:latest"
        build:
            context: ./app
            dockerfile: Dockerfile
        env_file:
            - env/app.env
        environment:
            - PORT=8000
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - ./app/data:/app/data
        restart: unless-stopped
