services:

    energyplus_ai:
        container_name: "energyplus_ai"
        image: "energyplus_ai:latest"
        build:
            context: "."
            dockerfile: "dev/Dockerfile"
        env_file:
            - env/app.env
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
            - ./data:/app/data
        depends_on:
            - redis
        restart: unless-stopped
