services:
    - type: web
      name: energyplus-ai
      env: docker
      plan: free
      dockerfilePath: app/Dockerfile
      dockerContext: app
      envVars:
          - key: PORT
            value: 8000
